<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Role extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Role_model');
    } 

    /*
     * Listing of roles
     */
    function index()
    {
        $data['roles'] = $this->Role_model->get_all_roles();

        $this->load->view('role/index',$data);
    }

    /*
     * Adding a new role
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
            );
            
            $role_id = $this->Role_model->add_role($params);
            redirect('role/index');
        }
        else
        {
            $this->load->view('role/add');
        }
    }  

    /*
     * Editing a role
     */
    function edit($id_rol)
    {   
        // check if the role exists before trying to edit it
        $role = $this->Role_model->get_role($id_rol);
        
        if(isset($role['id_rol']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
                );

                $this->Role_model->update_role($id_rol,$params);            
                redirect('role/index');
            }
            else
            {   
                $data['role'] = $this->Role_model->get_role($id_rol);
    
                $this->load->view('role/edit',$data);
            }
        }
        else
            show_error('The role you are trying to edit does not exist.');
    } 

    /*
     * Deleting role
     */
    function remove($id_rol)
    {
        $role = $this->Role_model->get_role($id_rol);

        // check if the role exists before trying to delete it
        if(isset($role['id_rol']))
        {
            $this->Role_model->delete_role($id_rol);
            redirect('role/index');
        }
        else
            show_error('The role you are trying to delete does not exist.');
    }
    
}
