<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Tipo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_model');
    } 

    /*
     * Listing of tipo
     */
    function index()
    {
        $data['tipo'] = $this->Tipo_model->get_all_tipo();

        $this->load->view('tipo/index',$data);
    }

    /*
     * Adding a new tipo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
            );
            
            $tipo_id = $this->Tipo_model->add_tipo($params);
            redirect('tipo/index');
        }
        else
        {
            $this->load->view('tipo/add');
        }
    }  

    /*
     * Editing a tipo
     */
    function edit($id_tipo)
    {   
        // check if the tipo exists before trying to edit it
        $tipo = $this->Tipo_model->get_tipo($id_tipo);
        
        if(isset($tipo['id_tipo']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
                );

                $this->Tipo_model->update_tipo($id_tipo,$params);            
                redirect('tipo/index');
            }
            else
            {   
                $data['tipo'] = $this->Tipo_model->get_tipo($id_tipo);
    
                $this->load->view('tipo/edit',$data);
            }
        }
        else
            show_error('The tipo you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo
     */
    function remove($id_tipo)
    {
        $tipo = $this->Tipo_model->get_tipo($id_tipo);

        // check if the tipo exists before trying to delete it
        if(isset($tipo['id_tipo']))
        {
            $this->Tipo_model->delete_tipo($id_tipo);
            redirect('tipo/index');
        }
        else
            show_error('The tipo you are trying to delete does not exist.');
    }
    
}
